import 'package:library_sys/model/book.dart';

final demoBooks = [
  Book(
    name: 'Introduction to Object Oriented Programming',
    author: 'MC McGraww Hil',
    numAvailable: 20,
    location: '2F6',
    subjectName: 'Computer Science',
  ),
  Book(
    name: 'Introduction to Object Oriented Programming',
    author: 'MC McGraww Hil',
    numAvailable: 20,
    location: '2F6',
    subjectName: 'Computer Science',
  ),
  Book(
    name: 'Introduction to Object Oriented Programming',
    author: 'MC McGraww Hil',
    numAvailable: 20,
    location: '2F6',
    subjectName: 'Computer Science',
  ),
  Book(
    name: 'Introduction to Object Oriented Programming',
    author: 'MC McGraww Hil',
    numAvailable: 20,
    location: '2F6',
    subjectName: 'Computer Science',
  ),
  Book(
    name: 'Introduction to Object Oriented Programming',
    author: 'MC McGraww Hil',
    numAvailable: 20,
    location: '2F6',
    subjectName: 'Computer Science',
  ),
  Book(
    name: 'Introduction to Object Oriented Programming',
    author: 'MC McGraww Hil',
    numAvailable: 20,
    location: '2F6',
    subjectName: 'Computer Science',
  ),
  Book(
    name: 'Introduction to Object Oriented Programming',
    author: 'MC McGraww Hil',
    numAvailable: 20,
    location: '2F6',
    subjectName: 'Computer Science',
  ),
  Book(
    name: 'Introduction to Object Oriented Programming',
    author: 'MC McGraww Hil',
    numAvailable: 20,
    location: '2F6',
    subjectName: 'Computer Science',
  ),
  Book(
    name: 'Introduction to Object Oriented Programming',
    author: 'MC McGraww Hil',
    numAvailable: 20,
    location: '2F6',
    subjectName: 'Computer Science',
  ),
  Book(
    name: 'Introduction to Object Oriented Programming',
    author: 'MC McGraww Hil',
    numAvailable: 20,
    location: '2F6',
    subjectName: 'Computer Science',
  ),
  Book(
    name: 'Introduction to Object Oriented Programming',
    author: 'MC McGraww Hil',
    numAvailable: 20,
    location: '2F6',
    subjectName: 'Computer Science',
  ),
  Book(
    name: 'Introduction to Object Oriented Programming',
    author: 'MC McGraww Hil',
    numAvailable: 20,
    location: '2F6',
    subjectName: 'Computer Science',
  ),
  Book(
    name: 'Introduction to Object Oriented Programming',
    author: 'MC McGraww Hil',
    numAvailable: 20,
    location: '2F6',
    subjectName: 'Computer Science',
  ),
  Book(
    name: 'Introduction to Object Oriented Programming',
    author: 'MC McGraww Hil',
    numAvailable: 20,
    location: '2F6',
    subjectName: 'Computer Science',
  ),
  Book(
    name: 'Introduction to Object Oriented Programming',
    author: 'MC McGraww Hil',
    numAvailable: 20,
    location: '2F6',
    subjectName: 'Computer Science',
  ),
  Book(
    name: 'Introduction to Object Oriented Programming',
    author: 'MC McGraww Hil',
    numAvailable: 20,
    location: '2F6',
    subjectName: 'Computer Science',
  ),
];
