import 'package:library_sys/model/book.dart';

final demoBooks = [
  Book(
    name: 'Introduction to Object Oriented Programming',
    author: 'MC McGraww Hil',
    numAvailable: 20,
    location: '2F6',
    branchName: 'Computer Science',
    subjectName: 'Programming Languages',
  ),
  Book(
      name: 'Signals and Systems',
      author: 'Oppenheim, Wilsky and Nawab',
      numAvailable: 23,
      location: '3A2',
      subjectName: 'Signals and Systems',
      branchName: 'Electronics & Communications'),
  Book(
    name: 'Probabilistic Methods of Signals and System Analysis',
    author: 'Cooper G.R and C. D. McGillem',
    numAvailable: 15,
    location: '3B1',
    subjectName: 'Signals and Systems',
    branchName: 'Electronics & Communications',
  ),
  Book(
    name: 'Electronic Devices and Circuit',
    author: 'Robert L. Boylestad',
    numAvailable: 17,
    location: '2F5',
    subjectName: 'Analog Electronics',
    branchName: 'Electronics & Communications',
  ),
  Book(
    name: 'Microelectronic Circuits ',
    author: 'A. S. Sedra and K. C. Smith',
    numAvailable: 10,
    location: '1A3',
    subjectName: 'Analog Electronics',
    branchName: 'Electronics & Communications',
  ),
  Book(
    name: 'Op-Amps and Linear Integrated Circuits',
    author: 'Ramakant A. Gayakwad',
    numAvailable: 12,
    location: '1A4',
    subjectName: 'Analog Electronics',
    branchName: 'Electronics & Communications',
  ),
  Book(
    name: 'Semiconductor Physics and Devices',
    author: 'Donald A Neamen',
    numAvailable: 18,
    location: '1B2',
    subjectName: 'Electronic Devices',
    branchName: 'Electronics & Communications',
  ),
  Book(
    name: 'Solid State Electronics Devices',
    author: 'Streetman and Banerjee',
    numAvailable: 28,
    location: '1B6',
    subjectName: 'Electronic Devices',
    branchName: 'Electronics & Instrumentation',
  ),
  Book(
    name: 'Network Analysis and Synthesis',
    author: 'A Chakraborty',
    numAvailable: 30,
    location: '1C2',
    subjectName: 'Network Analysis and Synthesis',
    branchName: 'Electronics & Communications',
  ),
  Book(
    name: 'Network theory',
    author: 'Smarajit Ghosh',
    numAvailable: 25,
    location: '1C5',
    subjectName: 'Network Analysis and Synthesis',
    branchName: 'Electrical Engineering',
  ),
  Book(
    name: 'Principles of Engineering Thermodynamics',
    author: 'Moran, Shappiro, Boettner and Bailey',
    numAvailable: 20,
    location: '2A1',
    subjectName: 'Basic Thermodynamics',
    branchName: 'Civil Engineering',
  ),
  Book(
    name: 'Thermodynamics: An Engineering Approach',
    author: 'Cengel and Boles : Thermodynamics',
    numAvailable: 10,
    location: '2A4',
    subjectName: 'Basic Thermodynamics',
    branchName: 'Civil Engineering',
  ),
  Book(
    name: 'Strength of Materials',
    author: 'G.H.Ryder',
    numAvailable: 28,
    location: '2D3',
    subjectName: 'STRENGTH OF MATERIALS',
    branchName: 'Mechanical Engineering',
  ),
  Book(
    name: 'Mechanics of Materials',
    author: 'Pytel and Singer',
    numAvailable: 18,
    location: '2D4',
    subjectName: 'STRENGTH OF MATERIALS',
    branchName: 'Civil Engineering',
  ),
  Book(
    name: 'Microprocessor & Interfacing',
    author: 'D. Hall',
    numAvailable: 8,
    location: '1E2',
    subjectName: 'MICROPROCESSORS AND SYSTEM PROGRAMMING',
    branchName: 'Electronics & Communications',
  ),
  Book(
    name: 'Advanced 80386 Programming Techniques',
    author: 'J. Turley',
    numAvailable: 9,
    location: '1E7',
    subjectName: 'MICROPROCESSORS AND SYSTEM PROGRAMMING',
    branchName: 'Electronics & Communications',
  ),
  Book(
    name: 'Communication Systems',
    author: 'Simon Haykin',
    numAvailable: 15,
    location: '1F5',
    subjectName: 'PRINCIPLE OF COMMUNICATION ENGINEERING',
    branchName: 'Electronics & Communications',
  ),
  Book(
    name: 'Communication Systems Engineering',
    author: 'Proakis & Salehi',
    numAvailable: 18,
    location: '1F6',
    subjectName: 'PRINCIPLE OF COMMUNICATION ENGINEERING',
    branchName: 'Electronics & Communications',
  ),
  Book(
    name: 'Digital communication',
    author: 'Simon Haykin',
    numAvailable: 19,
    location: '3A2',
    subjectName: 'DIGITAL COMMUNICATION',
    branchName: 'Electronics & Communications',
  ),
  Book(
    name: 'Modern Digital and Analog',
    author: 'B.P.Lathi',
    numAvailable: 16,
    location: '3A6',
    subjectName: 'DIGITAL COMMUNICATION',
    branchName: 'Electronics & Communications',
  ),
  Book(
    name: 'Principle of Industrial Instrumentation',
    author: 'D. Patranabis',
    numAvailable: 2,
    location: '3A3',
    subjectName: 'MEASUREMENT AND INSTRUMENTATION',
    branchName: 'Electronics & Communications',
  ),
  Book(
    name: 'Power Electronics- Converters, Application and Design',
    author: 'N. Mohan',
    numAvailable: 24,
    location: '3C3',
    subjectName: 'POWER ELECTRONICS',
    branchName: 'Electrical Engineering',
  ),
  Book(
    name: 'Fundamentals of Electrical Drives',
    author: 'G.K Dubey',
    numAvailable: 25,
    location: '3D7',
    subjectName: 'POWER ELECTRONICS',
    branchName: 'Electrical Engineering',
  ),
];
